### ISSUE TITLE
Will this ever be made?

### ISSUE THREAD

**Issue by MattCowley** [adamdodev/autoprefixer-php-native#1]
Just found this as I personally don't use Node and would love to automate our CSS compiling process.
Any eta on completion?

**Comment by adamdodev** [comment]
Hi Matt,

Probably not unfortunately, we don't have a use case for it any more and it would be quite a big job (and probably be really slow to boot).

If you fancied making a go of it the notes in the readme should get you started, though there might be better tools around now.

**Comment by MattCowley** [comment]
Ah right, ok, will have a go and see where I get!

I haven't found any autoprefixer apis/php tools anywhere so hopefully this will work as we don't use Node but want to automate our compiling process.

**Comment by MattCowley** [comment]
How would I go about compiling it into a php file I can begin to use and play around with?
